// Copyright 2021 Tencent Inc. All rights reserved.
//
// 商家转账
//
// * 场景及业务流程：     商户可通过该产品实现同时向多个用户微信零钱进行转账的操作，可用于发放奖金补贴、佣金货款结算、员工报销等场景。
// [https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0](https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0)
// * 接入步骤：     * 商户在微信支付商户平台开通“批量转账到零钱”产品权限，并勾选“使用API方式发起转账”。
// * 调用批量转账接口，对多个用户微信零钱发起转账。
// *调用查询批次接口，可获取到转账批次详情及当前状态。
// * 调用查询明细接口，可获取到单条转账明细详情及当前状态。
//
// API version: 1.0.5

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.transfer.model;

import com.google.gson.annotations.SerializedName;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

/**
 * InitiateBatchTransferResponse
 */
public class InitiateTransferResponse {
  /**
   * 【商户单号】 商户系统内部的商家单号，要求此参数只能由数字、大小写字母组成，在商户系统内部唯一
   */
  @SerializedName("out_bill_no")
  private String outBillNo;

  /**
   * 微信批次单号 说明：微信批次单号，微信商家转账系统返回的唯一标识
   */
  @SerializedName("transfer_bill_no")
  private String transferBillNo;

  /**
   * 【单据创建时间】 单据受理成功时返回，按照使用rfc3339所定义的格式，格式为yyyy-MM-DDThh:mm:ss+TIMEZONE
   */
  @SerializedName("create_time")
  private String createTime;

  /**
   * 【单据状态】 商家转账订单状态
   * ACCEPTED:  转账已受理，可原单重试（非终态）。
   * <p>
   * PROCESSING:  转账锁定资金中。如果一直停留在该状态，建议检查账户余额是否足够，如余额不足，可充值后再原单重试（非终态）。
   * <p>
   * WAIT_USER_CONFIRM:  待收款用户确认，当前转账单据资金已锁定，可拉起微信收款确认页面进行收款确认（非终态）。
   * <p>
   * TRANSFERING:  转账中，可拉起微信收款确认页面再次重试确认收款（非终态）。
   * <p>
   * SUCCESS:  转账成功，表示转账单据已成功（终态）。
   * <p>
   * FAIL:  转账失败，表示该笔转账单据已失败。若需重新向用户转账，请重新生成单据并再次发起（终态）。
   * <p>
   * CANCELING:  转账撤销中，商户撤销请求受理成功，该笔转账正在撤销中，需查单确认撤销的转账单据状态（非终态）。
   * <p>
   * CANCELLED:  转账撤销完成，代表转账单据已撤销成功（终态）
   */
  @SerializedName("state")
  private State state;

  /**
   * 【跳转领取页面的package信息】 跳转微信支付收款页的package信息，
   * APP调起用户确认收款或者JSAPI调起用户确认收款 时需要使用的参数。
   * 仅当转账单据状态为WAIT_USER_CONFIRM时返回
   *
   * @return
   */
  @SerializedName("package_info")
  private String packageInfo;


  public String getOutBillNo() {
    return outBillNo;
  }

  public void setOutBillNo(String outBillNo) {
    this.outBillNo = outBillNo;
  }

  public String getTransferBillNo() {
    return transferBillNo;
  }

  public void setTransferBillNo(String transferBillNo) {
    this.transferBillNo = transferBillNo;
  }

  public String getCreateTime() {
    return createTime;
  }

  public void setCreateTime(String createTime) {
    this.createTime = createTime;
  }

  public State getState() {
    return state;
  }

  public void setState(State state) {
    this.state = state;
  }

  public String getPackageInfo() {
    return packageInfo;
  }

  public void setPackageInfo(String packageInfo) {
    this.packageInfo = packageInfo;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateTransferResponse {\n");
    sb.append("    outBillNo: ").append(toIndentedString(outBillNo)).append("\n");
    sb.append("    transferBillNo: ").append(toIndentedString(transferBillNo)).append("\n");
    sb.append("    createTime: ").append(toIndentedString(createTime)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    packageInfo: ").append(toIndentedString(packageInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }
}
