// Copyright 2021 Tencent Inc. All rights reserved.
//
// 商家转账对外API
//
// * 场景及业务流程：     商户可通过该产品实现同时向多个用户微信零钱进行转账的操作，可用于发放奖金补贴、佣金货款结算、员工报销等场景。
// [https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0](https://pay.weixin.qq.com/index.php/public/product/detail?pid=108&productType=0)
// * 接入步骤：     * 商户在微信支付商户平台开通“批量转账到零钱”产品权限，并勾选“使用API方式发起转账”。     * 调用批量转账接口，对多个用户微信零钱发起转账。     *
// 调用查询批次接口，可获取到转账批次详情及当前状态。     * 调用查询明细接口，可获取到单条转账明细详情及当前状态。
//
// API version: 1.0.5

// Code generated by WechatPay APIv3 Generator based on [OpenAPI
// Generator](https://openapi-generator.tech); DO NOT EDIT.

package com.wechat.pay.java.service.transfer.model;

import com.google.gson.annotations.SerializedName;
import com.wechat.pay.java.core.cipher.Encryption;
import com.wechat.pay.java.service.transferbatch.model.TransferDetailInput;

import java.util.ArrayList;
import java.util.List;
import java.util.function.UnaryOperator;

import static com.wechat.pay.java.core.util.StringUtil.toIndentedString;

/**
 * InitiateBatchTransferRequest
 */
public class InitiateTransferRequest {
  /**
   * 商户appid 说明：申请商户号的appid或商户号绑定的appid（企业号corpid即为此appid）
   */
  @SerializedName("appid")
  private String appid;

  /**
   * 【商户单号】 商户系统内部的商家单号，要求此参数只能由数字、大小写字母组成，在商户系统内部唯一
   */
  @SerializedName("out_bill_no")
  private String outBillNo;

  /**
   * 【转账场景ID】 该笔转账使用的转账场景，可前往“商户平台-产品中心-商家转账”中申请。
   * 如：1000（现金营销），1006（企业报销）等
   */
  @SerializedName("transfer_scene_id")
  private String transferSceneId;

  /**
   * 批次备注 说明：转账说明，UTF8编码，最多允许32个字符
   */
  @SerializedName("openid")
  private String openid;


  /**
   * 【收款用户姓名】 收款方真实姓名。若传入收款用户姓名，微信支付会校验收款用户与输入姓名是否一致。
   * 转账金额>=2,000元时，必须传入该值。
   * 该字段需要加密传入，参考微信支付公钥加密敏感信息指引(推荐)、平台证书加密敏感信息指引
   */

  @Encryption
  @SerializedName("user_name")
  private String userName;

  /**
   * 【转账备注】 转账备注，用户收款时可见该备注信息，UTF8编码，最多允许32个字符
   */
  @SerializedName("transfer_amount")
  private Long transferAmount;


  /**
   * 【转账备注】 转账备注，用户收款时可见该备注信息，UTF8编码，最多允许32个字符
   */
  @SerializedName("transfer_remark")
  private String transferRemark;

  /**
   * 【通知地址】 异步接收微信支付结果通知的回调地址，通知url必须为公网可访问的URL，必须为HTTPS，不能携带参数。
   */
  @SerializedName("notify_url")
  private String notifyUrl;


  /**
   * 转账明细列表 说明：发起批量转账的明细列表，最多一千笔
   */
  @Encryption
  @SerializedName("transfer_scene_report_infos")
  private List<TransferDetailInput> transferSceneReportInfos = new ArrayList<TransferDetailInput>();


  public String getAppid() {
    return appid;
  }

  public void setAppid(String appid) {
    this.appid = appid;
  }


  public String getTransferSceneId() {
    return transferSceneId;
  }

  public void setTransferSceneId(String transferSceneId) {
    this.transferSceneId = transferSceneId;
  }

  public String getOpenid() {
    return openid;
  }

  public void setOpenid(String openid) {
    this.openid = openid;
  }

  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public Long getTransferAmount() {
    return transferAmount;
  }

  public void setTransferAmount(Long transferAmount) {
    this.transferAmount = transferAmount;
  }

  public String getTransferRemark() {
    return transferRemark;
  }

  public void setTransferRemark(String transferRemark) {
    this.transferRemark = transferRemark;
  }

  public String getNotifyUrl() {
    return notifyUrl;
  }

  public void setNotifyUrl(String notifyUrl) {
    this.notifyUrl = notifyUrl;
  }



  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InitiateBatchTransferRequest {\n");
    sb.append("    appid: ").append(toIndentedString(appid)).append("\n");
    sb.append("    outBatchNo: ").append(toIndentedString(outBillNo)).append("\n");
    sb.append("    transferSceneId: ").append(toIndentedString(transferSceneId)).append("\n");
    sb.append("    openid: ").append(toIndentedString(openid)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    transferAmount: ").append(toIndentedString(transferAmount)).append("\n");
    sb.append("    transferRemark: ").append(toIndentedString(transferRemark)).append("\n");
    sb.append("    notifyUrl: ").append(toIndentedString(notifyUrl)).append("\n");
    sb.append("    transferSceneReportInfos: ").append(toIndentedString(transferSceneReportInfos)).append("\n");
    sb.append("    transferSceneId: ").append(toIndentedString(transferSceneId)).append("\n");
    sb.append("}");
    return sb.toString();
  }


  public InitiateTransferRequest cloneWithCipher(UnaryOperator<String> s) {
    InitiateTransferRequest copy = new InitiateTransferRequest();
    copy.appid = appid;
    copy.outBillNo = outBillNo;
    copy.transferSceneId = transferSceneId;
    copy.openid = openid;
    copy.userName = userName;
    copy.transferAmount = transferAmount;
    copy.transferRemark = transferRemark;
    copy.notifyUrl = notifyUrl;
    if (transferSceneReportInfos != null && transferSceneReportInfos.size() != 0) {
      // arr
      copy.transferSceneReportInfos = new ArrayList<>();
      for (TransferDetailInput val : transferSceneReportInfos) {
        if (val != null) {
          copy.transferSceneReportInfos.add(val.cloneWithCipher(s));
        }
      }
    }
    return copy;
  }
}
